# Generated by Django 4.2.7 on 2024-04-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_address_date_of_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-date_of_creation', 'title'], 'verbose_name': 'адрес', 'verbose_name_plural': 'адреса'},
        ),
    ]
