# Generated by Django 4.2.7 on 2024-04-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateField(blank=True, help_text='В формате "дд.мм.гггг"', null=True, verbose_name='Дата изготовления'),
        ),
    ]
